name: Build Image On Release

on:
  release:
    types: [published]
  pull_request:
    branches:
      - 'main'
    types: [ assigned ]    

jobs:
  call-workflow:
    uses: linuxserver-labs/docker-actions/.github/workflows/build-image.yml@v4
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "your_spotify"
    secrets:
      scarf_token: ${{ secrets.SCARF_TOKEN }}
