name: Build Image On Release

on:
  release:
    types: [published]
  pull_request:

jobs:
  call-workflow:
    uses: linuxserver-labs/docker-actions/.github/workflows/build-image.yml@v5
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "your_spotify"
      release_type: "github_commit"
      release_url: "https://api.github.com/repos/Yooooomi/your_spotify/commits/master"
    secrets:
      scarf_token: ${{ secrets.SCARF_TOKEN }}
